import './globals.css'
import Nav from './components/Nav'
import { getUser } from '@/content/getUser'
import { User } from '@prisma/client'





export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const newUser = await getUser()
  return (
    <html lang="en">
      <body className="bg-gray-300  shadow-slate-950"> <Nav newUser ={newUser} />        {children}</body>
    </html>
  )
}
